# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'table_test',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no_a', models.IntegerField(default=0)),
                ('name_a', models.CharField(max_length=25)),
            ],
        ),
    ]
