# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_delete_testtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no_a', models.IntegerField(default=0)),
                ('name_a', models.CharField(max_length=25)),
            ],
        ),
    ]
