# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=70)),
                ('c_email_id', models.CharField(max_length=255, unique=True)),
                ('c_alternate_email_id', models.CharField(blank=True, max_length=255, null=True)),
                ('c_contact_number', models.IntegerField()),
                ('c_alternate_contact_number', models.IntegerField(blank=True, null=True)),
                ('c_address', models.CharField(max_length=175)),
                ('c_state_ut', models.CharField(max_length=70)),
                ('c_district', models.CharField(max_length=70)),
                ('c_pincode', models.IntegerField()),
                ('c_alternate_address', models.CharField(max_length=175)),
                ('c_alternate_state', models.CharField(max_length=70)),
                ('c_alternate_district', models.CharField(max_length=70)),
                ('c_alternate_pincode', models.IntegerField()),
                ('c_date_of_birth', models.DateField()),
                ('c_f_name', models.CharField(max_length=70)),
                ('c_gender', models.CharField(max_length=12)),
                ('c_category', models.CharField(max_length=12)),
                ('c_differently_abled', models.TextField()),
                ('c_is_bpl', models.TextField()),
                ('c_annual_family_income', models.IntegerField()),
                ('c_educational_qualification', models.CharField(max_length=25)),
                ('c_work_experience_months', models.IntegerField(blank=True, null=True)),
                ('c_work_experience_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('c_current_location_state_ut', models.CharField(max_length=25)),
                ('c_current_location_district', models.CharField(max_length=25)),
                ('c_preferred_trainig_state_ut', models.CharField(max_length=35)),
                ('c_sector', models.CharField(blank=True, max_length=255, null=True)),
                ('c_course', models.CharField(blank=True, max_length=255, null=True)),
                ('c_is_ready_to_relocate', models.TextField()),
                ('c_max_fee', models.IntegerField(blank=True, null=True)),
                ('c_is_agree', models.TextField()),
            ],
            options={
                'db_table': 'candidate_registration',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrainingCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_id', models.CharField(max_length=25)),
                ('training_center_state', models.CharField(max_length=25)),
                ('training_center_district', models.CharField(blank=True, max_length=25, null=True)),
                ('parliamentary_constituency', models.CharField(blank=True, max_length=25, null=True)),
                ('training_partner', models.CharField(blank=True, max_length=200, null=True)),
                ('training_center_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sector_skill_council', models.CharField(blank=True, max_length=255, null=True)),
                ('job_role_name', models.CharField(blank=True, max_length=255, null=True)),
                ('qp_code', models.CharField(max_length=50)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('no_of_hours', models.IntegerField(blank=True, null=True)),
                ('target_allocated', models.IntegerField(blank=True, null=True)),
                ('center_poc_name', models.CharField(blank=True, max_length=150, null=True)),
                ('center_poc_email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'training_center',
                'managed': True,
            },
        ),
    ]
