# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_login_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_details',
            name='user_date_joined',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='login_details',
            name='user_last_login',
            field=models.DateField(blank=True, null=True),
        ),
    ]
