# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170321_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='course_sector',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.SectorSkillCouncil'),
        ),
    ]
