# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_courseinfo_course_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCenterCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.CourseInfo')),
                ('training_center_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.TrainingCenter')),
            ],
        ),
    ]
