# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_trainingcentercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_start_data', models.DateField(default=django.utils.timezone.now)),
                ('batch_end_data', models.DateField(default=django.utils.timezone.now)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CourseInfo')),
                ('training_center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TrainingCenter')),
            ],
        ),
    ]
