# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170321_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFeedbackDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfd_subject', models.CharField(blank=True, max_length=255)),
                ('cfd_detail', models.TextField(blank=True)),
                ('cfd_feedback_date', models.DateField(default=django.utils.timezone.now)),
                ('cfd_rating', models.IntegerField(default=1)),
                ('cfd_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CourseInfo')),
                ('cfd_training_center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TrainingCenter')),
                ('cfd_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='StateIndia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatewiseDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_district_name', models.CharField(max_length=255)),
                ('sd_state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.StateIndia')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scr_registration_date', models.DateField(default=django.utils.timezone.now)),
                ('scr_is_completed', models.BooleanField(default=False)),
                ('scr_completion_date', models.DateField(default=django.utils.timezone.now)),
                ('scr_course_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.CourseInfo')),
                ('scr_training_center_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.TrainingCenter')),
                ('scr_user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.AppUser')),
            ],
        ),
    ]
