# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_trainingcenter_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchinfo',
            old_name='batch_end_data',
            new_name='batch_assesment_date',
        ),
        migrations.RenameField(
            model_name='batchinfo',
            old_name='batch_start_data',
            new_name='batch_end_date',
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='batch_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
