# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20170331_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eu_email', models.CharField(max_length=255, unique=True)),
                ('eu_password', models.CharField(max_length=128)),
                ('eu_last_login', models.DateField(blank=True, null=True)),
                ('eu_date_joined', models.DateField(default=django.utils.timezone.now)),
                ('eu_name', models.CharField(max_length=70)),
            ],
        ),
    ]
