# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_employeruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeruser',
            name='eu_date_joined',
        ),
        migrations.RemoveField(
            model_name='employeruser',
            name='eu_last_login',
        ),
    ]
