# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20170401_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jp_job_desc', models.CharField(max_length=255)),
                ('jp_required_starting_date', models.DateField(default=django.utils.timezone.now)),
                ('jp_required_ending_date', models.DateField(default=django.utils.timezone.now)),
                ('jp_salary_low', models.IntegerField(default=0)),
                ('jp_salary_high', models.IntegerField(default=0)),
                ('jp_employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EmployerUser')),
                ('jp_job_role_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.JobRole')),
            ],
        ),
    ]
