# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_jobprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AadharDummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_aadhar_no', models.CharField(max_length=12, unique=True)),
                ('ad_fullname', models.CharField(max_length=255)),
                ('ad_mother_name', models.CharField(max_length=255)),
                ('ad_year_of_birth', models.IntegerField(default=0)),
                ('ad_gender', models.CharField(max_length=10)),
                ('ad_address', models.TextField()),
            ],
        ),
    ]
