# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_aadhardummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhardummy',
            name='ad_address',
            field=models.TextField(blank=True),
        ),
    ]
