# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_aadhardummy_ad_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhardummy',
            name='ad_mobile_no',
            field=models.CharField(default='', max_length=12),
        ),
    ]
