# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_aadhardummy_ad_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhardummy',
            name='ad_district',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='aadhardummy',
            name='ad_state',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='aadhardummy',
            name='ad_mother_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aadhardummy',
            name='ad_year_of_birth',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_alternate_address',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_alternate_district',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_alternate_pincode',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_alternate_state',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_annual_family_income',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_category',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_current_location_district',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_current_location_state_ut',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_differently_abled',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_educational_qualification',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_f_name',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_is_agree',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_is_bpl',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_is_ready_to_relocate',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_pincode',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_preferred_training_state_ut',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
