# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20170401_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_date_of_birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_is_bpl',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
