# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20170401_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_annual_family_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_differently_abled',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_is_agree',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
