# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20170401_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateregistration',
            name='c_is_ready_to_relocate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
