# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20170401_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcenter',
            name='tc_area',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trainingcenter',
            name='tc_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='trainingcenter',
            name='tc_no_of_equipments',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='trainingcenter',
            name='tc_no_of_faculties',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
