# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20170401_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCenterJobRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.JobRole')),
                ('training_center_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.TrainingCenter')),
            ],
        ),
    ]
