# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_gpstrainingcenter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GpsTrainingCenter',
        ),
        migrations.AddField(
            model_name='trainingcenter',
            name='tc_lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trainingcenter',
            name='tc_lon',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
