# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20170402_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcenter',
            name='center_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
