# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20170402_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcenter',
            name='center_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
