# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20170402_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='course_level',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='course_minimum_qualification',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='course_no_of_days',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
