# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_certifiedtraineelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchinfo',
            name='batch_no_of_seats',
            field=models.IntegerField(default=0),
        ),
    ]
