# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_batchinfo_batch_no_of_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchinfo',
            name='batch_last_date_registration',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
