# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-24 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_candidateregistration_c_is_certified'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighAuthCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ha_email', models.CharField(max_length=255, unique=True)),
                ('ha_password', models.CharField(max_length=128)),
            ],
        ),
    ]
